version: '3.8'

services:
    htmx_server:
        build:
            context: ./
            dockerfile: ./docker/htmx_server.dockerfile
        ports:
            - '4000:4000'
        restart: always
        volumes:
            - ./packages/htmx_server/:/app/packages/htmx_server/
        # environment:
        #     - NODE_ENV=production
