version: '3.8'

services:
    htmx_server:
        build:
            context: ./
            dockerfile: ./packages/htmx_server/Dockerfile
        ports:
            - '4000:4000'
        # environment:
        #     - NODE_ENV=production
