import { QueryProvider } from "@repo/ui/query-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<html lang="en">
			<QueryProvider>
				<body>{children}</body>
			</QueryProvider>
		</html>
	);
}
